### ISSUE TITLE
Verify that ngrok url has changed before updating to Facebook

### ISSUE THREAD

**Issue by AlexGustafsson** [botpress/botpress-messenger#8]
Every time botpress is restarted, botpress-messenger connects to Facebook and triggers the "Upgraded messenger app webhook with new ngrok url" notification. This happens even when the ngrok url hasn't actually changed. Therefore I think that the url should be checked to see if it has actually been changed before updating to Facebook, not just doing it every time.

**Comment by slvnperron** [comment]
@AlexGustafsson thanks for creating this issue. The reason why it's updating the webhook every time is because when you check the 'Use ngrok' checkbox, it starts an ngrok process in the background for you (so you don't have to spawn ngrok yourelf). The problem with this approach is that if you kill the bot process, ngrok also gets killed, thus the url changes.

If you are using a Ngrok that you spawned yourself, you should not check the Ngrok checkbox. Does that make more sense? I think this is not obvious and should be explained better in the UI. What do you think?

**Comment by AlexGustafsson** [comment]
That's totally understandable. I misunderstood the option and was spawning my own instance of Ngrok. 

Perhaps the wording "use Ngrok" could be improved. Spawning an instance of Ngrok on my own is _using_ Ngrok. Perhaps something in the likes of "Automatically start Ngrok" would be a bit more accurate. Furthermore, adding "pop-over on question mark" (#5) could provide greater detail.

**Comment by slvnperron** [comment]
100% in agreement. Excellent feedback, thanks! We'll update the module in the next build 👍

**Comment by CostaC** [comment]
Had this confusion also.  

Option should be called something like "Use Botpress internal ngrok".

"Automatically start Ngrok" could still be confused with the host system's ngrok

**Comment by kalanka29** [comment]
@slvnperron : i cannot find the ngrok checkbox available in my botpress ,so that I can't run the messenger bot locally.what should I do ? plz help

**Comment by slvnperron** [comment]
@kalanka29 Please get ngrok or pagekite and update the hostname manually from either the UI or the botpress-messenger.config.yml file
